### ISSUE TITLE
ng-loading depends on angular-material

### ISSUE THREAD

**Issue by chillyistkult** [maseh87/ng-loading#18]
This breaks a lot of applications and does not make any sense for a simple loading-bar. For example if you have a web application built with bootstrap you don't want to include another front-end framework. My suggestion is to strip unnecessary dependencies and make the module as light as possible.

**Comment by sopheakmorm** [comment]
Can I use it with bootstrap framework ?

**Comment by chillyistkult** [comment]
It will break your styles since angular-material and bootstrap are not compatible.
